### ISSUE TITLE
TUL@sky: Infopath design checker fungerer ikke - adresse byttet? #104

### ISSUE THREAD

**Issue by tommyalmendingen** [tommyalmendingen/TUL-akseptansetest#12]
## Beskrivelse
Rapportert inn av:
PMH - SKD

I gamle tul så er adressen:
http://tul-spwb.ai.basefarm.net/designchecker/_vti_bin/FormsServices.asmx

Hva er den nye adressen?

==
Prøv:
T:\SKD\A01 a-melding\A01 141205 rev220801\A01_a-melding.xsn
Infopath > File > Design Checker

==
Prøv:
T:\SKD\A01 a-melding\A01 141205 rev220801\A01_a-melding.xsn
Infopath > File > Design Checker

## Skjermbilder
![image](https://user-images.githubusercontent.com/45939254/182349265-124bdb1d-606f-4616-b18a-90491c101aaf.png)

**Comment by tommyalmendingen** [comment]
Lukker denne etter svar fra SKD:
""Ja, det fungerte – saken er løst og kan lukkes (jeg oppdaterer intern Howto)"

**Comment by xmrsa** [comment]
Hvordan finner vi andre dødelige ut hvilken adresse vi skal bruke?

**Comment by tommyalmendingen** [comment]
Vi vanlige dødelige kan bruke denne:
http://tul.altinn.cloud/designchecker/_vti_bin/FormsServices.asmx

Jeg skal legge dette inn på infosiden også.

mvh
Tommy

Fra: Mari Romundset Sandelien ***@***.***>
Sendt: tirsdag 9. august 2022 13:10
Til: tommyalmendingen/TUL-akseptansetest ***@***.***>
Kopi: Almendingen, Tommy Flæsen Kvåle ***@***.***>; State change ***@***.***>
Emne: Re: [tommyalmendingen/TUL-akseptansetest] ***@***.***: Infopath design checker fungerer ikke - adresse byttet? #104 (Issue #12)

[ Ekstern e-post ]

Hvordan finner vi andre dødelige ut hvilken adresse vi skal bruke?

-
